# Generated by Django 4.2.2 on 2023-07-03 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodista', models.CharField(choices=[('Maria Plaza', 'Maria Plaza'), ('Isabel Caro', 'Isabel Caro'), ('Cesar Vasquez', 'Cesar Vasquez')], max_length=100)),
                ('categoria', models.CharField(choices=[('POPULAR', 'POPULAR'), ('POLITICA', 'POLITICA'), ('DEPORTE', 'DEPORTE')], max_length=50)),
                ('palabra_clave', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=100, null=True)),
                ('contenido', models.TextField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='noticias/')),
            ],
        ),
        migrations.CreateModel(
            name='NuevoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido_paterno', models.CharField(max_length=20)),
                ('apellido_materno', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('contrasena', models.CharField(blank=True, max_length=10, null=True)),
                ('activo', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
