# Generated by Django 4.2.2 on 2023-07-04 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_noticia_nuevousuario_alter_task_datecompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nuevousuario',
            old_name='contrasena',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='nuevousuario',
            name='password2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
