# Generated by Django 4.2.2 on 2023-07-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_contrasena_nuevousuario_password1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nuevousuario',
            name='username',
            field=models.CharField(default='default_username', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nuevousuario',
            name='password1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nuevousuario',
            name='password2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='nuevousuario',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
