# Generated by Django 4.2.2 on 2023-07-04 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_nuevousuario_username_alter_nuevousuario_password1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
