# Generated by Django 4.2.2 on 2023-07-06 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='noticias'),
        ),
    ]
